from typing import Dict, List, Union
from exp_utils import AC, Precision

input_configs: Dict[str, List[Dict[str, Union[AC, Precision, int]]]] = {
    "hf_T5": [
        {"batch_size": 6, "seq_len": 512, "precision": Precision.MP, "ac": AC.NONE, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 4, "seq_len": 1024, "precision": Precision.HP, "ac": AC.NONE, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 1, "seq_len": 2048, "precision": Precision.HP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 2, "seq_len": 1024, "precision": Precision.FP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 1, "seq_len": 2048, "precision": Precision.MP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 1, "seq_len": 2048, "precision": Precision.HP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 1, "seq_len": 2048, "precision": Precision.FP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
    ],
    "timm_vit": [
        {"batch_size": 32, "seq_len": -1, "precision": Precision.FP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.MP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.HP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 128, "seq_len": -1, "precision": Precision.HP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.MP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 256, "seq_len": -1, "precision": Precision.HP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.FP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
    ],
    "hf_clip": [
        {"batch_size": 32, "seq_len": 20, "precision": Precision.FP, "ac": AC.NONE, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": 20, "precision": Precision.MP, "ac": AC.NONE, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": 20, "precision": Precision.HP, "ac": AC.FULL, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 32, "seq_len": 20, "precision": Precision.FP, "ac": AC.NONE, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": 20, "precision": Precision.MP, "ac": AC.NONE, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 128, "seq_len": 20, "precision": Precision.HP, "ac": AC.FULL, "image_size": 336, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": 20, "precision": Precision.FP, "ac": AC.FULL, "image_size": 336, "num_denoising_steps": -1},
    ],
    "llama_v3_1b": [
        {"batch_size": 12, "seq_len": 1024, "precision": Precision.FP, "ac": AC.AUTO, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 16, "seq_len": 1024, "precision": Precision.FP, "ac": AC.AUTO, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 10, "seq_len": 2048, "precision": Precision.FP, "ac": AC.AUTO, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 6, "seq_len": 4096, "precision": Precision.FP, "ac": AC.AUTO, "image_size": -1, "num_denoising_steps": -1},
    ],
    "gemma_2b": [
        {"batch_size": 16, "seq_len": 512, "precision": Precision.HP, "ac": AC.AUTO, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 8, "seq_len": 1024, "precision": Precision.HP, "ac": AC.NONE, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 4, "seq_len": 2048, "precision": Precision.HP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 2, "seq_len": 4096, "precision": Precision.HP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 4, "seq_len": 1024, "precision": Precision.FP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 2, "seq_len": 2048, "precision": Precision.FP, "ac": AC.FULL, "image_size": -1, "num_denoising_steps": -1},
        {"batch_size": 2, "seq_len": 2048, "precision": Precision.MP, "ac": AC.NONE, "image_size": -1, "num_denoising_steps": -1},
    ],
    "timm_convnext_v2": [
        {"batch_size": 16, "seq_len": -1, "precision": Precision.FP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 32, "seq_len": -1, "precision": Precision.MP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.MP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 64, "seq_len": -1, "precision": Precision.HP, "ac": AC.NONE, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 128, "seq_len": -1, "precision": Precision.HP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 32, "seq_len": -1, "precision": Precision.FP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 256, "seq_len": -1, "precision": Precision.HP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
        {"batch_size": 128, "seq_len": -1, "precision": Precision.FP, "ac": AC.FULL, "image_size": 224, "num_denoising_steps": -1},
    ],
    "stable_diffusion": [
        {"batch_size": 160, "seq_len": 77, "precision": Precision.FP, "ac": AC.AUTO, "image_size": 256, "num_denoising_steps": 50},
        {"batch_size": 192, "seq_len": 77, "precision": Precision.FP, "ac": AC.AUTO, "image_size": 256, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 77, "precision": Precision.FP, "ac": AC.AUTO, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 80, "seq_len": 77, "precision": Precision.FP, "ac": AC.AUTO, "image_size": 512, "num_denoising_steps": 50},
    ],
    "flux": [
        {"batch_size": 1, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 16, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.FP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
    ],
    "stable_diffusion_mmdit": [
        {"batch_size": 1, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 16, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 64, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 128, "num_denoising_steps": 50},
        {"batch_size": 1, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 16, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 32, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
        {"batch_size": 64, "seq_len": 256, "precision": Precision.HP, "ac": AC.NONE, "image_size": 512, "num_denoising_steps": 50},
    ],
}